FluidTYPO3/fluidpages

Classes/Backend/BackendLayoutDataProvider.php
Classes/Backend/PageLayoutSelector.php
Classes/Provider/PageProvider.php
Classes/Service/PageService.php
Tests/Unit/Backend/PageLayoutSelectorTest.php

This change makes Fluidpages' classes utilise the new components of Flux which hold a view context and template path collections.
Depends: https://github.com/FluidTYPO3/flux/pull/758

[TASK] Switch to new Flux TemplatePaths/ViewContext objects

---

Classes/Backend/BackendLayoutDataProvider.php
Classes/Controller/PageController.php
Classes/Service/ConfigurationService.php

This fixes
1. a wrong comparison in the computation of `$hasMainAction` (*)
2. and gives `getBackendLayoutConfiguration()` the correct page provider
(\*) this might have been avoided *without* "Yoda conditions and explicit comparisons": compare
```php
$hasMainAction = TRUE === empty($row[PageProvider::FIELD_ACTION_MAIN]);
```
and
```php
$hasMainAction = !empty($row[PageProvider::FIELD_ACTION_MAIN]);
```

[BUGFIX] Correctly resolve Page vs. SubPageProvider, use page provider resolution for BackendLayoutConfiguration

---

ext_tables.php

Deprecated method. I don't want the message => `Usage of feInterface is
no longer part of the TYPO3 CMS Core` anymore ;-) ... and since core min. is 6.2 that's no problem.

[TASK] Get rid of the deprecation log

---

Classes/Backend/PageLayoutSelector.php

This patch makes ``PageLayoutSelector->renderOptions()`` return an empty string and thus does not render the package label if the provider extension does not provide any page layouts. See https://github.com/FluidTYPO3/flux/issues/839#issuecomment-105763399
Second try (see https://github.com/FluidTYPO3/fluidpages/pull/260), now following the CGL.

[TASK] Hide package label in page layout selector if no page layouts are provided

---

Classes/Backend/BackendLayoutDataProvider.php

Since 6.2.x doesn't have a get parameter 'M'
this commit adds a fallback to make hide the
colPos 18181 in page language view.

[BUGFIX] Add 6.2.x compatability

---

Classes/Controller/PageController.php
Tests/Unit/Controller/PageControllerTest.php

Enables putting 100% raw content into the `<head></head>` tag TYPO3 creates.

[FEATURE] Allow "HeaderCode" section in page templates

---

Classes/Service/PageService.php

Missing test of already found form of an overwritten template,
in function getAvailablePageTemplateFiles of PageService.php.
Now the correct configuration section is used.

[BUGFIX] Only template files of templateRootPaths.0 were used.

---

Classes/Provider/PageProvider.php
Tests/Unit/Provider/PageProviderTest.php

we should check for the existence of the Cache key instead of it being empty, because the Inherited Configuration often tends to be empty, which means, we retry this countless of times without any good reason. This results in a exponential growth old load time in relation to the amount of fields in a sheet.
On my MacBook Retina this resulted in ~ 35s load time for 10 simple input fields. 
Here's a little graph, that shows, the growth rate of the load time in relation to the amount of input fields in a page configuration sheet:

[TASK] Improve performance of PageProvider

---

Classes/Provider/PageProvider.php
Tests/Unit/Provider/PageProviderTest.php

moves the getInheritedConfiguration method out of the getInheritedPropertyValueByDottedPath to prevent thousands of unnecessary method calls.
Example with ~15 Fields on one page:
<table>
<tr>
<td>
Before these changes:
</td>
<td>
With this commit:
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

[TASK] More performance improvements

---

Classes/Provider/PageLanguageOverlayProvider.php
Classes/Provider/PageProvider.php
Classes/Provider/SubPageLanguageOverlayProvider.php
ext_conf_template.txt
ext_localconf.php
ext_tables.php
ext_tables.sql

Since TYPO3 7.6 the previous handling of translated page configuration has been deprecated and moved into the compatibility6 extension. To replace this functionality this commit introduces the flexform fields  for configuration to the  pages_language_overlay table and takes care of the overlaying of the affected configurations. This functionality is disable by default and can be activated through a toggle in the extension configuration.
related deprecation: [#70138 - Flex form language handling](https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.6/Deprecation-70138-FlexFormLanguageHandling.html#deprecation-70138-flex-form-language-handling)

[FEATURE] Replace deprecated configuration translation

---

Classes/Provider/PageLanguageOverlayProvider.php
Classes/Provider/SubPageLanguageOverlayProvider.php

"Replace deprecated configuration translation" introduced
new translation handling through pages_languages_overlay
but did not take into account to use the page to actually
show the correct flexform, instead the default was always
shown.

[BUGFIX] Show the correct flexform for the selected template

---

Classes/Service/PageService.php

This is required for Flux to know the controller which is needed to
assemble the correct path to search for template icons.
closes #309
closes FluidTYPO3/flux#1077

[BUGFIX] Set full template path on form option templateFile

---

CHANGELOG.md
Classes/Backend/PageLayoutSelector.php

Translates label if label is a reference - required since https://github.com/FluidTYPO3/flux/commit/81bb392f99ab1e30c30303ee5d885a7a44c9ff6f (which assumes consumers of labels do translation or support auto label translation in TYPO3).
Close: #313

[TASK] Translate label in custom template selector field

---

Classes/Provider/PageProvider.php

If a form is not set, the foreach should continue with the following branch in tree and not break.

Fix inheritance

---

ext_localconf.php
ext_tables.php

This adds a tiny XML DS for the two Fluidpages fields.
Without them, fluidpages fails since the recent FormEngine
FlexForm DS resolving refactor.

[TASK] Place a very basic default DS for compat with FormEngine

---

Classes/Service/PageService.php

This patch limits the number of SQL requests that will be
performed in setups which read page configurations
multiple times.
The performance drain is more expressed on setups where
developers retrieve page configurations, which happens
for example when retrieving page settings in custom menus
rendered with VHS.

[BUGFIX] Implement memoizer for page configuration

---

Classes/Controller/PageController.php

Code was using deprecated templateRootPath etc. singular names.

[BUGFIX] Switch to templateRootPaths etc. for raw page type

---

Tests/Unit/Backend/BackendLayoutDataProviderTest.php
Tests/Unit/Backend/BackendLayoutTest.php
Tests/Unit/Backend/PageLayoutSelectorTest.php
Tests/Unit/Backend/TemplateFileLayoutSelectorTest.php
Tests/Unit/Controller/PageControllerTest.php
Tests/Unit/Provider/PageProviderTest.php
Tests/Unit/Provider/SubPageProviderTest.php
Tests/Unit/Service/ConfigurationServiceTest.php
Tests/Unit/Service/PageServiceTest.php

Last remnants of mess (outside of formalities like `::class` and shorthand array in tests classes).

[TASK] Remove usages of deprecated phpunit methods

---

Classes/Backend/PageLayoutDataProvider.php
Tests/Unit/Backend/PageLayoutDataProviderTest.php

MiscellaneousUtility::getIconForTemplate can return NULL if no icon exists for the
specified template. Using MiscellaneousUtility::createIcon on this erroneous path
will lead to a TYPO3 exception on rendering the edit form (at least in v8.6.0).

[BUGFIX] Do not try to create option icon if template has no icon

---

Classes/Provider/PageProvider.php
Classes/Provider/SubPageLanguageOverlayProvider.php

Since there is no more language support in FlexForms,
and the entire FlexForm field gets added when the overlay
feature is enabled, we should be able to now drop the
support for merging values from languages, which in
turn would allow some methods to be removed from the
page provider pattern.

[REMOVAL] Remove language merging support

---

Classes/Provider/PageProvider.php

With current development branch, if you try to create a new page via the context menu in page tree, you get following error:
> Call to a member function getOption() on null 
>
> Error thrown in file
> typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php in line 186.
This new caching was introduced very recently with d4ce98a72f3eef6f1cb946ac99917185a5ff82f5

[BUGFIX] omit form caching if form === null

---

Configuration/TCA/Overrides/sys_template.php
ext_localconf.php

When called in ext_localconf.php the TCA is not loaded and thus the template not available.
The method documentation in Typo3 8.7 states:
- addStaticFile: FOR USE IN Configuration/TCA/Overrides/sys_template.php
- addTypoScriptConstants, addTypoScriptSetup: FOR USE IN ext_localconf.php FILES

[BUGFIX] moved addStaticFile() for non-autoload mode into TCA/Overrides/sys_template.php

---

Classes/Service/PageService.php
Tests/Unit/Service/PageServiceTest.php

This fix aborts the loop in `PageService->getPageTemplateConfiguration` early if the uid to fetch from the database becomes zero.
Database uids are guaranteed to start from one because uid 0 is reserved for the virtual page root.
This PR started out as a fix for #390 which has been addressed at the root in https://github.com/FluidTYPO3/flux/pull/1654, however I still consider it useful since it avoids a redundant database query.

[BUGFIX] Avoid root page query in getPageTemplateConfiguration
